### ISSUE TITLE
Доработать работу типографа.

### ISSUE THREAD

**Issue by maxisoft-git** [instantsoft/icms2#923]
**Используемая версия InstantCMS**: 2.10.x

**Версия PHP**:  7.1 

**Как воспроизвести проблему**:

Создать контент с полем html и обработкой типографом

**Воспроизводится ли проблема на демо http://demo.instantcms.ru/**: ДА

При оформлении текстов, используются теги span, при обработке типографом возможно использовать только атрибут style что не хорошо, так как стилей может быть много, логичнее добавить разрешенный тег id, class и data-* атрибуты.

**Comment by fuzegit** [comment]
> обавить разрешенный тег id, class и data-* атрибуты

не уверен, что пользователям нужно давать ставить эти атрибуты. А для вебмастеров скорее нужно сделать отключение типографа для определенных групп или как то иначе.

**Comment by fuzegit** [comment]
Права сделать на сам типограф, а не на вызов хука html_filter.

**Comment by maxisoft-git** [comment]
Как вариант можно и так, главное чтобы можно было настроить эти права.

**Comment by bilarius** [comment]
Поддерживаю

**Comment by san-sanych-k** [comment]
Что касается разрешенных тегов в типографе и прочего разрешенного, где все что не разрешено отсеивается - добавьте пожалуйста hook'и чтобы можно было добавлять свои "разрешения" не исправляя код системы. Это полезно для использования типографа в своих компонентах где нужно добавить прочие специфические теги.

**Comment by geminisf** [comment]
Я за возможность добавления своих тегов и возможность изменения параметров тегов.

**Comment by zau4man** [comment]
В типограф нужно добавить проверку опции "Проверять HTTP referer" компонента Редиректы. И в зависимости от опции формировать атрибуты внешних ссылок в строке https://github.com/instantsoft/icms2/blob/2c94377fc57a52b799186579854264feeae46d28/system/controllers/typograph/hooks/html_filter.php#L165 (версия 2.12.1). Сейчас в 2.12.1 при включенной опции и формировании внешних ссылок через редирект переход по ссылке ведет на 404, так как браузер не передает реферер.

**Comment by bilarius** [comment]
Это мне?  =================================СОЗДАНИЕ САЙТОВ И МОБИЛЬНЫХ ПРИЛОЖЕНИЙМой сайт: http://инстант.рф Быстрые контакты:  https://vk.com/bilariusSkype: bilarius С ув.Алексей=================================Кошелек WMR: R495413856719ЯД: 41001127410089   01.04.2019, 17:59, "zau4man" <notifications@github.com>:В типограф нужно добавить проверку опции "Проверять HTTP referer" компонента Редиректы. И в зависимости от опции формировать атрибуты внешних ссылок в строке https://github.com/instantsoft/icms2/blob/2c94377fc57a52b799186579854264feeae46d28/system/controllers/typograph/hooks/html_filter.php#L165 (версия 2.12.1). Сейчас в 2.12.1 при включенной опции и формировании внешних ссылок через редирект переход по ссылке ведет на 404, так как браузер не передает реферер.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by bilarius** [comment]
Это вы наверно не мне отправляли)))  =================================СОЗДАНИЕ САЙТОВ И МОБИЛЬНЫХ ПРИЛОЖЕНИЙМой сайт: http://инстант.рф Быстрые контакты:  https://vk.com/bilariusSkype: bilarius С ув.Алексей=================================Кошелек WMR: R495413856719ЯД: 41001127410089   01.04.2019, 17:59, "zau4man" <notifications@github.com>:В типограф нужно добавить проверку опции "Проверять HTTP referer" компонента Редиректы. И в зависимости от опции формировать атрибуты внешних ссылок в строке https://github.com/instantsoft/icms2/blob/2c94377fc57a52b799186579854264feeae46d28/system/controllers/typograph/hooks/html_filter.php#L165 (версия 2.12.1). Сейчас в 2.12.1 при включенной опции и формировании внешних ссылок через редирект переход по ссылке ведет на 404, так как браузер не передает реферер.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by fuzegit** [comment]
@bilarius  вам на почту приходит рассылка - уведомление от комментариев. Всё что вы отвечаете в почте, добавляется в комментарии на GitHub.

**Comment by dvduck** [comment]
Небольшая проблема с заменой тире на дефис в типографе решена, но, хотелось бы иметь такую возможность в настраиваемых опциях типографа. Спасибо! )

**Comment by fuzegit** [comment]
https://github.com/instantsoft/icms2/commit/9397d66f57484b9d974b6639f3765ab379d56380
